export interface IDatosImpresion {  

DireccionPunto: string,
Telefono: string,
Telefono2: string,
AbrevTipoServicio: string ,
AceptadoSUNAT: string,
ClaveEncomienda: string ,
Cliente: string ,
ClienteConsignado: string ,
CodRubro: string ,
CodVenta: string ,
CodigoHash: string,
CodigoQR: string ,
Destino: string ,
Detalle: string ,
DireccionEmpresa: string ,
DireccionPuntoOrigen: string ,
DocumentoReferenciaExceso: string ,
FechaVenta: string ,
FechaViaje: string,
Gravada: string ,
HoraSalida: string ,
HoraSalidaCliente: string ,
Igv: string ,
NomCondicionPago: string ,
CodDocumento : string,
NomDocumento: string,
DireccionCliente : string,
NomEmpresa: string ,
NomUsuario: string ,
NroAsiento: string ,
NroClienteConsignado: string ,
NroDocumento: string ,
NroDocumentoIdentidad: string,
NroDocumentoPasajero : string,
Pasajero : string,
Origen: string,
PolizaSeguro: string ,
PuntoConsignado: string ,
RUCEmpresa: string ,
RutaImagenQR: string ,
Simbolo: string,
TelefonoEmpresa: string ,
Total: string,
TotalLetras: string,

}

