export interface IloginModel {
    CodAlmacen: number,
    CodCobranzaPlanilla: number,
    CodEmpresa: number,
    CodPersona: number,
    CodResultado: number,
    CodUsuario: number,
    CodUsuarioTipo: number,
    CodigoEmpresa: string,
    DesResultado:  string,
    IGV: number,
    MensajePendiente:  string,
    NomEmpleado: string,
    NomEmpresa:  string,
    NomUsuario:  string,
    TipoCambio: number,
    UltimoAcceso:  string,
    UltimoWeb:  string,
    FechaIngreso : string,
    IdImpresora : string
}
